ug4: VecMath Bridge
VecMath Bridge
ugbase » Bridge » Misc Bridge
Functions
static SmartPtr< vector1 > ug::MakeVec (number x)
static SmartPtr< vector2 > ug::MakeVec (number x, number y)
static SmartPtr< vector3 > ug::MakeVec (number x, number y, number z)
static SmartPtr< vector4 > ug::MakeVec (number x, number y, number z, number w)
template<typename TRegistry >
void ug::bridge::RegisterBridge_VecMath_ (TRegistry &reg, string parentGroup)
template<typename TRegistry >
static void ug::bridge::RegisterVecMathBridge_DimIndep (TRegistry &reg, string grp)
ug::UG_REGISTRY_DEFINE (RegisterBridge_VecMath)
Detailed Description
Function Documentation
MakeVec() [1/4]
static SmartPtr<vector1> ug::MakeVec (number x) static
MakeVec() [2/4]
static SmartPtr<vector2> ug::MakeVec (number x, number y) static
MakeVec() [3/4]
static SmartPtr<vector3> ug::MakeVec (number x, number y, number z) static
MakeVec() [4/4]
static SmartPtr<vector4> ug::MakeVec (number x, number y, number z, number w) static
Referenced by ug::bridge::RegisterVecMathBridge_DimIndep().
RegisterBridge_VecMath_()
template<typename TRegistry > void ug::bridge::RegisterBridge_VecMath_ (TRegistry & reg, string parentGroup)
References ug::bridge::RegisterVecMathBridge_DimIndep().
RegisterVecMathBridge_DimIndep()
template<typename TRegistry > static void ug::bridge::RegisterVecMathBridge_DimIndep (TRegistry & reg, string grp) static
References ug::MakeVec(), and UG_REGISTRY_CATCH_THROW.
Referenced by ug::bridge::RegisterBridge_VecMath_().
UG_REGISTRY_DEFINE()
ug::UG_REGISTRY_DEFINE (RegisterBridge_VecMath)