ug4: Bridge
Bridge
ugbase
Modules
Algebra Bridge
Discretization Bridge
Domain Bridge
Misc Bridge
Registry
Classes
struct ug::bridge::AlgebraTypeIDProvider
struct ug::bridge::RegisterAlgebraDependent< Functionality, TRegistry, List >
struct ug::bridge::RegisterDomain1dAlgebraDependent< Functionality, AlgebraList >
struct ug::bridge::RegisterDomain2d3dAlgebraDependent< Functionality, AlgebraList >
struct ug::bridge::RegisterDomain2dAlgebraDependent< Functionality, AlgebraList >
struct ug::bridge::RegisterDomain3dAlgebraDependent< Functionality, AlgebraList >
struct ug::bridge::RegisterDomainAlgebraDependent< Functionality, TRegistry, DomainList, AlgebraList >
struct ug::bridge::RegisterDomainDependent< Functionality, TRegistry, List >
Typedefs
typedef boost::mpl::list< end_boost_list > ug::bridge::CompileAlgebraList
typedef boost::mpl::list<> ug::bridge::CompileDomainList
Functions
template<typename TAlgebra >
std::string ug::bridge::GetAlgebraSuffix ()
returns the algebra-suffix (e.g. "CPU3", "CPUFlex")
template<typename TAlgebraTypeType >
std::string ug::bridge::GetAlgebraSuffix (const TAlgebraTypeType &algType)
returns the algebra-suffix (e.g. "CPU3", "CPUFlex")
template<typename TAlgebra >
std::string ug::bridge::GetAlgebraTag ()
returns the algebra-suffix (e.g. "alg=CPU3", "alg=CPUVariable")
template<typename TAlgebraTypeType >
std::string ug::bridge::GetAlgebraTag (const TAlgebraTypeType &algType)
returns the algebra-suffix (e.g. "alg=CPU3", "alg=CPUVariable")
template<int dim, typename TAlgebra >
std::string ug::bridge::GetDimensionAlgebraSuffix ()
returns the algebra-dim-suffix for a domain (e.g. "3dCPU1")
template<int dim, typename TAlgebra >
std::string ug::bridge::GetDimensionAlgebraTag ()
returns the dim-tag for a domain (e.g. "dim=3d;alg=CPU1;")
template<typename TAlgebraTypeType >
std::string ug::bridge::GetDimensionAlgebraTag (int dim, const TAlgebraTypeType &algType)
returns dim tag at runtime (e.g. "dim=3d;alg=CPU1;")
template<int dim>
std::string ug::bridge::GetDimensionSuffix ()
returns the dim-suffix for a domain (e.g. "3d")
template<int dim>
std::string ug::bridge::GetDimensionTag ()
returns the dim-tag for a domain (e.g. "dim=3d")
std::string ug::bridge::GetDimensionTag (int dim)
returns dim tag at runtime (e.g. "dim=3d")
template<typename TDomain , typename TAlgebra >
std::string ug::bridge::GetDomainAlgebraSuffix ()
returns the dim-suffix for a domain (e.g. "3dCPU1")
template<typename TDomain , typename TAlgebra >
std::string ug::bridge::GetDomainAlgebraTag ()
returns the dim-tag for a domain (e.g. "dim=3d;alg=CPU1;")
template<typename TDomain >
std::string ug::bridge::GetDomainSuffix ()
returns the dim-suffix for a domain (e.g. "3d")
template<typename TDomain >
std::string ug::bridge::GetDomainTag ()
returns the dim-tag for a domain (e.g. "dim=3d")
int ug::bridge::GetUGDim ()
returns the dimension to which UG was initialized through InitUG
Registry & ug::bridge::GetUGRegistry ()
returns the default registry used in ug
void ug::bridge::InitBridge ()
calls RegisterStandardInterfaces
void ug::bridge::InitUG (int dim, const AlgebraType &algebraType)
Sets the default classes of class-groups based on a tags using default DoFManager.
template<typename Functionality , typename TRegistry = Registry>
void ug::bridge::RegisterCommon_ (TRegistry &reg, std::string grp)
template<typename Functionality , typename TRegistry = Registry>
void ug::bridge::RegisterDimension1dDependent (TRegistry &reg, std::string grp)
template<typename Functionality , typename TRegistry = Registry>
void ug::bridge::RegisterDimension2d3dDependent (TRegistry &reg, std::string grp)
template<typename Functionality , typename TRegistry = Registry>
void ug::bridge::RegisterDimension2dDependent (TRegistry &reg, std::string grp)
template<typename Functionality , typename TRegistry = Registry>
void ug::bridge::RegisterDimension3dDependent (TRegistry &reg, std::string grp)
template<typename Functionality , typename TRegistry = Registry>
void ug::bridge::RegisterDimensionDependent_ (TRegistry &reg, std::string grp)
template<typename Functionality , typename TRegistry = Registry>
void ug::bridge::RegisterDomain1dDependent (TRegistry &reg, std::string grp)
template<typename Functionality , typename TRegistry = Registry>
void ug::bridge::RegisterDomain2d3dDependent (TRegistry &reg, std::string grp)
template<typename Functionality , typename TRegistry = Registry>
void ug::bridge::RegisterDomain2dDependent (TRegistry &reg, std::string grp)
template<typename Functionality , typename TRegistry = Registry>
void ug::bridge::RegisterDomain3dDependent (TRegistry &reg, std::string grp)
UG_API void ug::bridge::RegisterStandardBridges (Registry &reg, std::string grp=UG4_GRP)
registers all standard interfaces.
ug::UG_REGISTRY_DECL (RegisterBridge_DiscCommon, Registry &reg, std::string grp=bridge::UG4_GRP)
Registers the common part of lib_discretization.
ug::UG_REGISTRY_DECL (RegisterBridge_Domain, Registry &reg, std::string grp=bridge::UG4_GRP)
Registers the domain object and related methods.
ug::UG_REGISTRY_DECL (RegisterBridge_DomainRayTracing, Registry &reg, std::string grp=bridge::UG4_GRP)
Registers methods to perform ray-tracing on domains.
ug::UG_REGISTRY_DECL (RegisterBridge_ElemDiscs, Registry &reg, std::string grp=bridge::UG4_GRP)
Registers the element discretizations.
ug::UG_REGISTRY_DECL (RegisterBridge_Grid, Registry &reg, std::string grp=bridge::UG4_GRP)
registers lib-grid interface methods at the registry.
ug::UG_REGISTRY_DECL (RegisterBridge_LoadBalancing, Registry &reg, std::string grp=bridge::UG4_GRP)
registers LoadBalancer, partitioners, etc
ug::UG_REGISTRY_DECL (RegisterBridge_Misc, Registry &reg, std::string grp=bridge::UG4_GRP)
ug::UG_REGISTRY_DECL (RegisterBridge_OrthoPoly, Registry &reg, std::string grp=bridge::UG4_GRP)
registers orthogonal polynomials
ug::UG_REGISTRY_DECL (RegisterBridge_PCL, Registry &reg, std::string grp=bridge::UG4_GRP)
registers methods for a parallel environment
ug::UG_REGISTRY_DECL (RegisterBridge_PeriodicBoundary, Registry &reg, std::string grp=bridge::UG4_GRP)
Registers periodic boundary identification.
ug::UG_REGISTRY_DECL (RegisterBridge_Profiler, Registry &reg, std::string grp=bridge::UG4_GRP)
registers access to profiling functions at the registry
ug::UG_REGISTRY_DECL (RegisterBridge_Raster, Registry &reg, std::string grp=bridge::UG4_GRP)
registers rasters, e.g. for 1,2,3 dimensional image data or density distributions
ug::UG_REGISTRY_DECL (RegisterBridge_ReferenceMappingTest, Registry &reg, std::string grp=bridge::UG4_GRP)
registers reference mapping test functionality (common)
ug::UG_REGISTRY_DECL (RegisterBridge_Refinement, Registry &reg, std::string grp=bridge::UG4_GRP)
Registers refiners and marking methods.
ug::UG_REGISTRY_DECL (RegisterBridge_Selection, Registry &reg, std::string grp=bridge::UG4_GRP)
Registers methods to perform selections on the elements of a domain.
ug::UG_REGISTRY_DECL (RegisterBridge_Test, Registry &reg, std::string grp=bridge::UG4_GRP)
registers tests for the interface methods at the registry.
ug::UG_REGISTRY_DECL (RegisterBridge_Transform, Registry &reg, std::string grp=bridge::UG4_GRP)
Registers methods to transform the vertices of a domain.
ug::UG_REGISTRY_DECL (RegisterBridge_UserData, Registry &reg, std::string grp=bridge::UG4_GRP)
registers user data
ug::UG_REGISTRY_DECL (RegisterBridge_Util, Registry &reg, std::string grp=bridge::UG4_GRP)
registers some util methods like path-access and script-parsing.
ug::UG_REGISTRY_DECL (RegisterBridge_VecMath, Registry &reg, std::string grp=bridge::UG4_GRP)
Registers types and functions for 1, 2, 3 and 4 dimensional vector math.
Variables
static const size_t ug::bridge::NUM_ALGEBRA_TYPES = boost::mpl::size<CompileAlgebraList>::type::value - 1
const char * ug::bridge::UG4_GRP = "/ug4"
string for ug4 group
Detailed Description
Typedef Documentation
CompileAlgebraList
typedef boost::mpl::list< end_boost_list > ug::bridge::CompileAlgebraList
CompileDomainList
typedef boost::mpl::list<> ug::bridge::CompileDomainList
Function Documentation
GetAlgebraSuffix() [1/2]
template<typename TAlgebra > std::string ug::bridge::GetAlgebraSuffix ()
returns the algebra-suffix (e.g. "CPU3", "CPUFlex")
References ug::bridge::GetAlgebraSuffix().
GetAlgebraSuffix() [2/2]
template<typename TAlgebraTypeType > std::string ug::bridge::GetAlgebraSuffix (const TAlgebraTypeType & algType) inline
returns the algebra-suffix (e.g. "CPU3", "CPUFlex")
References UG_THROW.
Referenced by ug::bridge::GetAlgebraSuffix().
GetAlgebraTag() [1/2]
template<typename TAlgebra > std::string ug::bridge::GetAlgebraTag ()
returns the algebra-suffix (e.g. "alg=CPU3", "alg=CPUVariable")
References ug::bridge::GetAlgebraTag().
GetAlgebraTag() [2/2]
template<typename TAlgebraTypeType > std::string ug::bridge::GetAlgebraTag (const TAlgebraTypeType & algType) inline
returns the algebra-suffix (e.g. "alg=CPU3", "alg=CPUVariable")
References UG_THROW.
Referenced by ug::bridge::GetAlgebraTag(), ug::bridge::GetDimensionAlgebraTag(), and ug::bridge::InitUG().
GetDimensionAlgebraSuffix()
template<int dim, typename TAlgebra > std::string ug::bridge::GetDimensionAlgebraSuffix ()
returns the algebra-dim-suffix for a domain (e.g. "3dCPU1")
GetDimensionAlgebraTag() [1/2]
template<int dim, typename TAlgebra > std::string ug::bridge::GetDimensionAlgebraTag ()
returns the dim-tag for a domain (e.g. "dim=3d;alg=CPU1;")
GetDimensionAlgebraTag() [2/2]
template<typename TAlgebraTypeType > std::string ug::bridge::GetDimensionAlgebraTag (int dim, const TAlgebraTypeType & algType) inline
returns dim tag at runtime (e.g. "dim=3d;alg=CPU1;")
References ug::bridge::GetAlgebraTag(), and ug::bridge::GetDimensionTag().
GetDimensionSuffix()
template<int dim> std::string ug::bridge::GetDimensionSuffix ()
returns the dim-suffix for a domain (e.g. "3d")
GetDimensionTag() [1/2]
template<int dim> std::string ug::bridge::GetDimensionTag ()
returns the dim-tag for a domain (e.g. "dim=3d")
Referenced by ug::bridge::GetDimensionAlgebraTag(), and ug::bridge::InitUG().
GetDimensionTag() [2/2]
std::string ug::bridge::GetDimensionTag (int dim) inline
returns dim tag at runtime (e.g. "dim=3d")
GetDomainAlgebraSuffix()
template<typename TDomain , typename TAlgebra > std::string ug::bridge::GetDomainAlgebraSuffix ()
returns the dim-suffix for a domain (e.g. "3dCPU1")
GetDomainAlgebraTag()
template<typename TDomain , typename TAlgebra > std::string ug::bridge::GetDomainAlgebraTag ()
returns the dim-tag for a domain (e.g. "dim=3d;alg=CPU1;")
GetDomainSuffix()
template<typename TDomain > std::string ug::bridge::GetDomainSuffix ()
returns the dim-suffix for a domain (e.g. "3d")
GetDomainTag()
template<typename TDomain > std::string ug::bridge::GetDomainTag ()
returns the dim-tag for a domain (e.g. "dim=3d")
GetUGDim()
UG_API int ug::bridge::GetUGDim ()
returns the dimension to which UG was initialized through InitUG
If ug::bridge::InitUG hasn't been called, the method returns -1.
References ug::bridge::UG4_DIM.
Referenced by ug::bridge::RegisterBridge_InitUG_().
GetUGRegistry()
Registry & ug::bridge::GetUGRegistry ()
returns the default registry used in ug
Referenced by ug::bridge::ClassInstantiations(), ug::bridge::ClassUsage(), ug::bridge::lua::GetBestMatchingMember(), ug::bridge::GetClassesCompletitions(), ug::script::GetDefaultLuaState(), ug::bridge::GetGlobalFunctionInfo(), ug::bridge::GetLuaGlobals(), ug::bridge::GetMemberFunctionCompletitions(), ug::bridge::GetMemberFunctionInfo(), ug::bridge::InitBridge(), ug::bridge::InitUG(), Java_edu_gcsc_vrl_ug_UG__1ugInit(), ug::bridge::LuaList_cfunctions(), ug::bridge::LuaList_classes(), ug::bridge::PostRegisterTest(), ug::bridge::ScriptHasClass(), ug::bridge::ScriptHasClassGroup(), ug::bridge::ScriptPrintClassHierarchy(), ug_check_registry(), ug::script::UGGetClassGroup(), ug::bridge::UGTypeInfo(), and ug::bridge::WriteLUAObject2().
InitBridge()
UG_API void ug::bridge::InitBridge ()
calls RegisterStandardInterfaces
calls RegisterStandardInterfaces and LoadPlugins if UG_PLUGINS is defined
References ug::bridge::GetUGRegistry(), PROFILE_FUNC, and ug::bridge::RegisterStandardBridges().
Referenced by ug_init_bridge(), and ug::UGInit().
InitUG()
UG_API void ug::bridge::InitUG (int dim, const AlgebraType & algType)
Sets the default classes of class-groups based on a tags using default DoFManager.
Referenced by ug::bridge::RegisterBridge_InitUG_().
RegisterCommon_()
template<typename Functionality , typename TRegistry = Registry> void ug::bridge::RegisterCommon_ (TRegistry & reg, std::string grp)
RegisterDimension1dDependent()
template<typename Functionality , typename TRegistry = Registry> void ug::bridge::RegisterDimension1dDependent (TRegistry & reg, std::string grp)
RegisterDimension2d3dDependent()
template<typename Functionality , typename TRegistry = Registry> void ug::bridge::RegisterDimension2d3dDependent (TRegistry & reg, std::string grp)
RegisterDimension2dDependent()
template<typename Functionality , typename TRegistry = Registry> void ug::bridge::RegisterDimension2dDependent (TRegistry & reg, std::string grp)
RegisterDimension3dDependent()
template<typename Functionality , typename TRegistry = Registry> void ug::bridge::RegisterDimension3dDependent (TRegistry & reg, std::string grp)
RegisterDimensionDependent_()
template<typename Functionality , typename TRegistry = Registry> void ug::bridge::RegisterDimensionDependent_ (TRegistry & reg, std::string grp)
RegisterDomain1dDependent()
template<typename Functionality , typename TRegistry = Registry> void ug::bridge::RegisterDomain1dDependent (TRegistry & reg, std::string grp)
RegisterDomain2d3dDependent()
template<typename Functionality , typename TRegistry = Registry> void ug::bridge::RegisterDomain2d3dDependent (TRegistry & reg, std::string grp)
RegisterDomain2dDependent()
template<typename Functionality , typename TRegistry = Registry> void ug::bridge::RegisterDomain2dDependent (TRegistry & reg, std::string grp)
RegisterDomain3dDependent()
template<typename Functionality , typename TRegistry = Registry> void ug::bridge::RegisterDomain3dDependent (TRegistry & reg, std::string grp)
RegisterStandardBridges()
UG_API void ug::bridge::RegisterStandardBridges (Registry & reg, std::string grp = UG4_GRP)
registers all standard interfaces.
This method is called by the constructor of Registry automatically. You don't have to call it yourself!
UG_REGISTRY_DECL() [1/20]
ug::UG_REGISTRY_DECL (RegisterBridge_DiscCommon , Registry & reg, std::string grp = bridge::UG4_GRP)
Registers the common part of lib_discretization.
UG_REGISTRY_DECL() [2/20]
ug::UG_REGISTRY_DECL (RegisterBridge_Domain , Registry & reg, std::string grp = bridge::UG4_GRP)
Registers the domain object and related methods.
UG_REGISTRY_DECL() [3/20]
ug::UG_REGISTRY_DECL (RegisterBridge_DomainRayTracing , Registry & reg, std::string grp = bridge::UG4_GRP)
Registers methods to perform ray-tracing on domains.
UG_REGISTRY_DECL() [4/20]
ug::UG_REGISTRY_DECL (RegisterBridge_ElemDiscs , Registry & reg, std::string grp = bridge::UG4_GRP)
Registers the element discretizations.
UG_REGISTRY_DECL() [5/20]
ug::UG_REGISTRY_DECL (RegisterBridge_Grid , Registry & reg, std::string grp = bridge::UG4_GRP)
registers lib-grid interface methods at the registry.
This method is automatically invoked during the creation of the Registry.
UG_REGISTRY_DECL() [6/20]
ug::UG_REGISTRY_DECL (RegisterBridge_LoadBalancing , Registry & reg, std::string grp = bridge::UG4_GRP)
registers LoadBalancer, partitioners, etc
UG_REGISTRY_DECL() [7/20]
ug::UG_REGISTRY_DECL (RegisterBridge_Misc , Registry & reg, std::string grp = bridge::UG4_GRP)
UG_REGISTRY_DECL() [8/20]
ug::UG_REGISTRY_DECL (RegisterBridge_OrthoPoly , Registry & reg, std::string grp = bridge::UG4_GRP)
registers orthogonal polynomials
UG_REGISTRY_DECL() [9/20]
ug::UG_REGISTRY_DECL (RegisterBridge_PCL , Registry & reg, std::string grp = bridge::UG4_GRP)
registers methods for a parallel environment
UG_REGISTRY_DECL() [10/20]
ug::UG_REGISTRY_DECL (RegisterBridge_PeriodicBoundary , Registry & reg, std::string grp = bridge::UG4_GRP)
Registers periodic boundary identification.
UG_REGISTRY_DECL() [11/20]
ug::UG_REGISTRY_DECL (RegisterBridge_Profiler , Registry & reg, std::string grp = bridge::UG4_GRP)
registers access to profiling functions at the registry
UG_REGISTRY_DECL() [12/20]
ug::UG_REGISTRY_DECL (RegisterBridge_Raster , Registry & reg, std::string grp = bridge::UG4_GRP)
registers rasters, e.g. for 1,2,3 dimensional image data or density distributions
UG_REGISTRY_DECL() [13/20]
ug::UG_REGISTRY_DECL (RegisterBridge_ReferenceMappingTest , Registry & reg, std::string grp = bridge::UG4_GRP)
registers reference mapping test functionality (common)
UG_REGISTRY_DECL() [14/20]
ug::UG_REGISTRY_DECL (RegisterBridge_Refinement , Registry & reg, std::string grp = bridge::UG4_GRP)
Registers refiners and marking methods.
UG_REGISTRY_DECL() [15/20]
ug::UG_REGISTRY_DECL (RegisterBridge_Selection , Registry & reg, std::string grp = bridge::UG4_GRP)
Registers methods to perform selections on the elements of a domain.
UG_REGISTRY_DECL() [16/20]
ug::UG_REGISTRY_DECL (RegisterBridge_Test , Registry & reg, std::string grp = bridge::UG4_GRP)
registers tests for the interface methods at the registry.
This method is automatically invoked during the creation of the Registry.
UG_REGISTRY_DECL() [17/20]
ug::UG_REGISTRY_DECL (RegisterBridge_Transform , Registry & reg, std::string grp = bridge::UG4_GRP)
Registers methods to transform the vertices of a domain.
UG_REGISTRY_DECL() [18/20]
ug::UG_REGISTRY_DECL (RegisterBridge_UserData , Registry & reg, std::string grp = bridge::UG4_GRP)
registers user data
UG_REGISTRY_DECL() [19/20]
ug::UG_REGISTRY_DECL (RegisterBridge_Util , Registry & reg, std::string grp = bridge::UG4_GRP)
registers some util methods like path-access and script-parsing.
UG_REGISTRY_DECL() [20/20]
ug::UG_REGISTRY_DECL (RegisterBridge_VecMath , Registry & reg, std::string grp = bridge::UG4_GRP)
Registers types and functions for 1, 2, 3 and 4 dimensional vector math.
Variable Documentation
NUM_ALGEBRA_TYPES
const size_t ug::bridge::NUM_ALGEBRA_TYPES = boost::mpl::size<CompileAlgebraList>::type::value - 1 static
Referenced by ug::bridge::AlgebraTypeIDProvider::id().
UG4_GRP
const char * ug::bridge::UG4_GRP = "/ug4"
string for ug4 group